### PR TITLE
Entry Point resolution considers baseUrl

### PR DESCRIPTION
**Pull request by davidsk**
Updated the DefaultEntryPointResolver to accept relative EntryPoint paths

### CODE REVIEW

**Comment by jasonhjohnson** [comment]
Thanks man I'll give this a try as soon as they pull it into the master and update the nuget.

**Comment by CezarCretu** [comment]
I've published this commit as version 2.1.41, thank you for your contribution.

**Comment by jasonhjohnson** [comment]
I'm still getting the same issue. I deleted my overrides and rebuilt everything. Here are some helpful screenshots (maybe?):

http://take.ms/3e762 - Notice the "/app/app" part.

http://take.ms/RyHEW

http://take.ms/hJzo6

**Comment by davidsk** [comment]
Hi Jason,
 
Your screenshots are helpful.  I'm not sure precisely why the app folder is being duplicated in your path but I'll have a look.
 
Thanks,
 
Keith. 
 
Date: Wed, 18 Feb 2015 07:21:08 -0800

**Comment by davidsk** [comment]
Hi Jason

I can't reproduce your error using the latest nuget package (2.1.41.0)  and a fresh web project.  I'm not sure how you're defining your baseUrl outwith the HtmlHelper, I can't seem to do that.  Have you tried a literal value in the Url.Content() method?

Sample project here: http://1drv.ms/1vH1dKd

**Comment by jasonhjohnson** [comment]
David,

Do you have a an e-mail I can contact you at? Perhaps I can show you my setup with http://join.me?

Thanks,
Jason

**Comment by davidsk** [comment]
Hi Jason,

I not that familiar with the project I just fixed what didn't work for me.  I'd suggest updating your fork from master and then adding the RequireJSDotNet project to your solution - a break point on the resolve method will allow you to trace how it's building the path.
 
Failing that, you can email me at keithdavidson@hotmail.com.  A join.me session might take a bit of scheduling as I'm in the UK but I'm sure we could manage something.  

Cheers,

Keith.

**Pull request merged**
